blank_issues_enabled: false
contact_links:
  - name: "SPSUpdate Discussions"
    url: https://github.com/luigilink/SPSUpdate/discussions
    about: "To engage with the community and maintainers of SPSUpdate, please visit the discussions group. There, you can share feedback, ask questions, and collaborate with others working on SPSUpdate."
